Repository NIPOSoftwareBV/Nfield-SDK, pull requests merged in 2018-11, with the labels that each got.

#140 [Story] Prepare for new SurveyType EuroBarometerAdvanced
  Library/Models/SurveyType.cs
Labels: Team Purple :space_invader:

#138 Upgrade System.Net.Http package
  Library/Nfield.SDK.csproj
Labels: Team Blue

#143 Improve automation in SDK release
  README.md
  createnugetversion.ps1
  prerelease.ps1
  publish-release.ps1
Labels: Team White

#144 [Story] Improve automation in SDK release
  README.md
  createnugetversion.ps1
  prerelease.ps1
  publish-release.ps1
Labels: Team White
