Repository NIPOSoftwareBV/Nfield-SDK, pull requests merged in 2018-04, with the labels that each got.

#92 Delete appveyor.yml
  appveyor.yml
Labels: Team White

#96 Purple/add search survey
  Library/Infrastructure/NfieldSdkInitializer.cs
  Library/Models/Survey.cs
  Library/Services/INfieldRespondentSurveysService.cs
  Library/Services/Implementation/NfieldRespondentSurveysService.cs
  Tests/Services/NfieldRespondentSurveysServiceTests.cs
Labels: Team Purple

#97 search fields setting
  Library/Infrastructure/NfieldSdkInitializer.cs
  Library/Models/DomainSearchFieldsSetting.cs
  Library/Services/INfieldDomainSearchFieldsSettingService.cs
  Library/Services/Implementation/NfieldDomainSearchFieldsSettingService.cs
  Tests/Infrastructure/NfieldSdkInitializerTests.cs
Labels: Team Purple :space_invader:

#100 search fields setting tests
  Library/Services/Implementation/NfieldDomainSearchFieldsSettingService.cs
  Tests/Services/NfieldDomainSearchFieldsSettingServiceTests.cs
Labels: Team Purple :space_invader:

#101 Purple/change search respondent uri
  Library/Infrastructure/NfieldSdkInitializer.cs
  Library/Models/Survey.cs
  Library/Models/SurveyBase.cs
  Library/Services/INfieldSurveysSearchService.cs
  Library/Services/Implementation/NfieldSurveysSearchService.cs
  Tests/Services/NfieldSurveysSearchServiceTests.cs
Labels: Team Purple :space_invader:

#102 Use encoded query string to provide search value
  Library/Services/Implementation/NfieldSurveysSearchService.cs
  Tests/Services/NfieldSurveysSearchServiceTests.cs
Labels: Team Purple :space_invader:

#104 Purple/ci clear by interviewid
  Library/Services/INfieldSurveySampleService.cs
  Library/Services/Implementation/NfieldSurveySampleService.cs
  Tests/Services/NfieldSurveySampleTests.cs
Labels: Team Purple :space_invader:
