Repository NIPOSoftwareBV/Nfield-SDK, pull requests merged in 2019-07, with the labels that each got.

#167 Add cati survey type
  Library/Models/SurveyType.cs
Labels: Team Blue

#168 [Story] Introduce CATI survey type
  Library/Models/SurveyType.cs
  version.txt
Labels: Team Blue

#173 Get a specific survey group
  Library/Services/INfieldSurveyGroupService.cs
  Library/Services/Implementation/NfieldSurveyGroupService.cs
  Tests/Services/NfieldSurveyGroupServiceTests.cs
Labels: Team Red

#174 Add method to move survey
  Library/Services/INfieldSurveyGroupService.cs
  Library/Services/Implementation/NfieldSurveyGroupService.cs
  Tests/Extensions/HttpResponseMessageExtensionsTests.cs
  Tests/Nfield.SDK.Tests.csproj
  Tests/Services/NfieldExternalApisServiceTests.cs
  Tests/Services/NfieldInterviewersServiceTests.cs
  Tests/Services/NfieldLanguagesServiceTests.cs
  Tests/Services/NfieldSurveyGroupServiceTests.cs
  Tests/Services/NfieldSurveyRelocationsServiceTests.cs
  Tests/Services/NfieldSurveysServiceTests.cs
  Tests/Services/NfieldTranslationsServiceTests.cs
Labels: Team Red :steam_locomotive:

#175 Shared format
  .editorconfig
  Examples/NfieldInterviewersManagement.cs
  Examples/NfieldSamplingPointManagement.cs
  Examples/Program.cs
  Library/Exceptions/NfieldErrorException.cs
  Library/Exceptions/NfieldHttpResponseException.cs
  Library/Infrastructure/DependencyResolver.cs
  Library/Infrastructure/DependencyResolverExtensions.cs
  Library/Infrastructure/NfieldConnection.cs
  Library/Infrastructure/NfieldUtilityProvider.cs
  Library/Infrastructure/PathWrapper.cs
  Library/Models/DomainSearchFieldsSetting.cs
  Library/Models/InterviewDetailsModel.cs
  Library/Models/QuotaLevel.cs
  Library/Models/SampleFilter.cs
  Library/Models/SurveyInterviewerAssignmentModel.cs
  Library/Services/INfieldSurveysService.cs
  Library/Services/Implementation/NfieldBackgroundTasksService.cs
  Library/Services/Implementation/NfieldInterviewQualityService.cs
  Library/Services/Implementation/NfieldInterviewersService.cs
  Library/Services/Implementation/NfieldInterviewsService.cs
  Library/Services/Implementation/NfieldRespondentDataEncryptService.cs
  Library/Services/Implementation/NfieldSamplingPointInterviewerAssignmentsService.cs
  Library/Services/Implementation/NfieldSurveyFieldworkService.cs
  Library/Services/Implementation/NfieldSurveyInterviewerAssignmentsService.cs
  Library/Services/Implementation/NfieldSurveyPublishService.cs
  Library/Services/Implementation/NfieldSurveyResponseCodesService.cs
  Library/Services/Implementation/NfieldSurveySampleService.cs
  Library/Services/Implementation/NfieldSurveysService.cs
  Library/Utilities/NfieldEncryptionUtility.cs
  Nfield.SDK.sln
  Tests/Nfield.SDK.Tests.csproj
  Tests/Services/NfieldDomainSearchFieldsSettingServiceTests.cs
  Tests/Services/NfieldFieldworkOfficesServiceTests.cs
  Tests/Services/NfieldInterviewQualityServiceTests.cs
  Tests/Services/NfieldInterviewersServiceTests.cs
  Tests/Services/NfieldInterviewsServiceTests.cs
  Tests/Services/NfieldRespondentDataEncryptServiceTests.cs
  Tests/Services/NfieldSamplingPointInterviewerAssignmentsServiceTests.cs
  Tests/Services/NfieldSurveyFieldworkServiceTests.cs
  Tests/Services/NfieldSurveyInterviewersServiceTests.cs
  Tests/Services/NfieldSurveyInvitationImagesServiceTests.cs
  Tests/Services/NfieldSurveyInvitationTemplatesServiceTests.cs
  Tests/Services/NfieldSurveyInviteRespondentsServiceTests.cs
  Tests/Services/NfieldSurveyPublicIdsServiceTests.cs
  Tests/Services/NfieldSurveyPublishServiceTests.cs
  Tests/Services/NfieldSurveyRelocationsServiceTests.cs
  Tests/Services/NfieldSurveyResponseCodesServiceTests.cs
  Tests/Services/NfieldSurveySampleTests.cs
  Tests/Services/NfieldSurveyScriptServiceTests.cs
  Tests/Services/NfieldSurveysServiceTests.cs
  Tests/Utilities/NfieldEncryptionUtilityTests.cs
Labels: Team Purple :space_invader:
