Repository NIPOSoftwareBV/Nfield-SDK, pull requests merged in 2021-07, with the labels that each got.

#230 [AB#82785] Purple/Change SurveyResponseCodesController to also accept the relocation URL parameter
  Library/Models/SurveyResponseCode.cs
  Library/Services/Implementation/NfieldSurveyResponseCodesService.cs
  Tests/Services/NfieldSurveyResponseCodesServiceTests.cs
  version.txt
Labels: Team Purple :space_invader:

#231 Add survey performance service
  Library/Infrastructure/NfieldSdkInitializer.cs
  Library/Models/MetricCounts.cs
  Library/Models/SurveyMetricCounts.cs
  Library/Models/SurveyMetrics.cs
  Library/Services/INfieldSurveyPerformanceService.cs
  Library/Services/Implementation/NfieldSurveyPerformanceService.cs
  version.txt
Labels: Team White

#232 [Story] Expose survey metrics through public api - AB#90702
  Library/Infrastructure/NfieldSdkInitializer.cs
  Library/Models/MetricCounts.cs
  Library/Models/SurveyMetricCounts.cs
  Library/Models/SurveyMetrics.cs
  Library/Services/INfieldSurveyPerformanceService.cs
  Library/Services/Implementation/NfieldSurveyPerformanceService.cs
  version.txt
Labels: Team White

#233 Bump Nfield.Quota from 4.0 to 5.0
  Library/Nfield.SDK.csproj
  version.txt
Labels: Team Red :steam_locomotive:

#235 [AB#88851] Story: Introduce no-dialer mode
  Library/Models/DialMode.cs
  Library/Services/INfieldSurveysService.cs
  Library/Services/Implementation/NfieldSurveysService.cs
  Tests/Services/NfieldSurveysServiceTests.cs
  version.txt
Labels: Team Blue
