Repository NIPOSoftwareBV/Nfield-SDK, pull requests merged in 2021-11, with the labels that each got.

#269 AB#95917 - API: add survey general settings endpoints(SDK)
  Library/Infrastructure/NfieldSdkInitializer.cs
  Library/Models/SurveyGeneralSetting.cs
  Library/Services/INfieldSurveyGeneralSettingsService.cs
  Library/Services/Implementation/NfieldSurveyGeneralSettingsService.cs
  Postman/SurveyGeneralSettings.postman_collection.json
  Tests/Services/NfieldSurveyGeneralSettingsServiceTests.cs
Labels: Team Yellow, Story :checkered_flag:

#272 Postman collection dor the DomainLanguage
  Postman/DomainLanguages.postman_collection.json
Labels: Team Yellow

#277 Yellow/public api surveyinterviewerassignments
  Postman/SurveyInterviewersAssignments.postman_collection.json
  Postman/SurveyResponseCodes.postman_collection.json
Labels: Team Yellow

#278 reuse model
  Library/Models/InterviewerAssignmentModel.cs
  Library/Models/SurveyInterviewerModel.cs
  Library/Services/INfieldSurveyInterviewersService.cs
  Library/Services/Implementation/NfieldSurveyInterviewersService.cs
  Tests/Services/NfieldInterviewerAssignmentsServiceTests.cs
  Tests/Services/NfieldSurveyInterviewersServiceTests.cs
Labels: Team Yellow

#275 Add Windows Forms sample using AAD authentication
  Examples/ConsoleApplication/ConsoleApplication.csproj
  Examples/ConsoleApplication/NfieldInterviewersManagement.cs
  Examples/ConsoleApplication/NfieldSampleManagement.cs
  Examples/ConsoleApplication/NfieldSamplingPointManagement.cs
  Examples/ConsoleApplication/Program.cs
  Examples/WindowsFormsApplication/ApplicationConfiguration.cs
  Examples/WindowsFormsApplication/MainForm.Designer.cs
  Examples/WindowsFormsApplication/MainForm.cs
  Examples/WindowsFormsApplication/MainForm.resx
  Examples/WindowsFormsApplication/Nfield.cs
  Examples/WindowsFormsApplication/Program.cs
  Examples/WindowsFormsApplication/WindowsFormsApplication.csproj
  Examples/WindowsFormsApplication/appsettings.json
  Examples/WindowsFormsApplication/images/AddAllNfieldPublicAPIPermissions.png
  Examples/WindowsFormsApplication/images/AddMobileDesktopApplication.png
  Examples/WindowsFormsApplication/images/AddPermission.png
  Examples/WindowsFormsApplication/images/AddPlatform.png
  Examples/WindowsFormsApplication/images/AppRegistrations.png
  Examples/WindowsFormsApplication/images/AuthenticationAfterAddPlatform.png
  Examples/WindowsFormsApplication/images/Consent.png
  Examples/WindowsFormsApplication/images/InitialAppDetails.png
  Examples/WindowsFormsApplication/images/NewRegistration.png
  Examples/WindowsFormsApplication/images/PermissionsAfterAdd.png
  Examples/WindowsFormsApplication/images/RedirectUris.png
  Examples/WindowsFormsApplication/images/RegisterApplication.png
  Examples/WindowsFormsApplication/images/SelectNfieldPublicAPI.png
  Examples/WindowsFormsApplication/readme.md
  Nfield.SDK.sln
  devops.yml
Labels: Team White, Story :checkered_flag:

#280 Add survey owner management to postman
  Postman/SurveyGeneralSettings.postman_collection.json
Labels: Team Yellow

#283 Add owner management to surveyGeneralSettingsService
  Library/Models/SurveyGeneralSettingsOwner.cs
  Library/Services/INfieldSurveyGeneralSettingsService.cs
  Library/Services/Implementation/NfieldSurveyGeneralSettingsService.cs
  Tests/Services/NfieldSurveyGeneralSettingsServiceTests.cs
Labels: Team Yellow

#281 API: Add survey owner management
  Library/Models/SurveyGeneralSettingsOwner.cs
  Library/Services/INfieldSurveyGeneralSettingsService.cs
  Library/Services/Implementation/NfieldSurveyGeneralSettingsService.cs
  Postman/SurveyGeneralSettings.postman_collection.json
  Tests/Services/NfieldSurveyGeneralSettingsServiceTests.cs
  version.txt
Labels: Team Yellow

#285 Get Assignments QuotaTargets Postman Collection
  Postman/SurveyInterviewersAssignments.postman_collection.json
Labels: Team Yellow

#287 Response codes counts unit tests
  Library/Services/Implementation/NfieldSurveyFieldworkService.cs
  Tests/Services/NfieldSurveyFieldworkServiceTests.cs
  version.txt
Labels: Team Yellow
