Repository NIPOSoftwareBV/Nfield-SDK, pull requests merged in 2022-10, with the labels that each got.

#350 Update postman collection with blacklist upload
  Postman/ExampleFiles/blacklist.csv
  Postman/Nfield Public API.postman_collection.json
Labels: Team Purple :space_invader:

#351 Add request to SDK
  Library/Infrastructure/NfieldSdkInitializer.cs
  Library/Models/Request.cs
  Library/Models/RequestHeader.cs
  Library/Models/RequestHttpMethod.cs
  Library/Services/INfieldRequestsService.cs
  Library/Services/Implementation/NfieldRequestsService.cs
  Postman/Nfield Public API.postman_collection.json
  Tests/Services/NfieldRequestsServiceTests.cs
  version.txt
Labels: Team White

#353 Implement blacklist upload
  Library/Infrastructure/NfieldSdkInitializer.cs
  Library/Models/BlacklistUploadStatus.cs
  Library/Services/INfieldBlacklistService.cs
  Library/Services/Implementation/NfieldBlacklistService.cs
  Tests/Services/NfieldBlacklistTests.cs
  version.txt
Labels: Team Purple :space_invader:

#355 Make it async
  Library/Services/Implementation/NfieldRequestsService.cs
  Tests/Services/NfieldRequestsServiceTests.cs
Labels: Team White

#356 Adds CapiInterviewers to the collection
  Library/Infrastructure/NfieldSdkInitializer.cs
  Library/Models/BlacklistUploadStatus.cs
  Library/Services/INfieldBlacklistService.cs
  Library/Services/Implementation/NfieldBlacklistService.cs
  Postman/ExampleFiles/blacklist.csv
  Postman/Nfield Public API.postman_collection.json
  Tests/Services/NfieldBlacklistTests.cs
  version.txt
Labels: Team Yellow

#358 [AB#117565] Purple/Issue [#2793] API interviewer endpoint difference
  Library/Models/CapiInterviewers/CapiInterviewer.cs
  Postman/Nfield Public API.postman_collection.json
  version.txt
Labels: Team Purple :space_invader:

#359 Support download blacklist
  Library/Services/Implementation/NfieldBlacklistService.cs
  Postman/Nfield Public API.postman_collection.json
  Tests/Services/NfieldBlacklistTests.cs
  version.txt
Labels: Team Purple :space_invader:

#352 [AB#116867] Story: Implement configuration for *REQUEST in public API
  Library/Infrastructure/NfieldSdkInitializer.cs
  Library/Models/Request.cs
  Library/Models/RequestHeader.cs
  Library/Models/RequestHttpMethod.cs
  Library/Services/INfieldRequestsService.cs
  Library/Services/Implementation/NfieldRequestsService.cs
  Postman/Nfield Public API.postman_collection.json
  Tests/Services/NfieldRequestsServiceTests.cs
  version.txt
Labels: Team White, Story :checkered_flag:

#354 [AB#116519] Purple/API for Uploading blacklist email addresses
  Library/Infrastructure/NfieldSdkInitializer.cs
  Library/Models/BlacklistUploadStatus.cs
  Library/Services/INfieldBlacklistService.cs
  Library/Services/Implementation/NfieldBlacklistService.cs
  Postman/ExampleFiles/blacklist.csv
  Postman/Nfield Public API.postman_collection.json
  Tests/Services/NfieldBlacklistTests.cs
  version.txt
Labels: Team Purple :space_invader:

#361 [AB#116814] API for Downloading blacklist email addresses
  Library/Services/INfieldBlacklistService.cs
  Library/Services/Implementation/NfieldBlacklistService.cs
  Postman/Nfield Public API.postman_collection.json
  Tests/Services/NfieldBlacklistTests.cs
  version.txt
Labels: Team Purple :space_invader:, Story :checkered_flag:

#362 Make tests async
  Tests/Services/NfieldRequestsServiceTests.cs
Labels: Team White
