Repository NIPOSoftwareBV/Nfield-SDK, pull requests merged in 2022-06, with the labels that each got.

#335 AB#103077 - (sdk) Remove obsolete endpoints
  Examples/ConsoleApplication/Program.cs
  Library/Extensions/NfieldLanguagesServiceExtensions.cs
  Library/Extensions/NfieldTranslationsServiceExtensions.cs
  Library/Infrastructure/NfieldSdkInitializer.cs
  Library/Services/INfieldDomainLanguageTranslationsService.cs
  Library/Services/INfieldLanguagesService.cs
  Library/Services/INfieldSurveyLanguageTranslationsService.cs
  Library/Services/INfieldSurveyRelocationsService.cs
  Library/Services/INfieldTranslationsService.cs
  Library/Services/Implementation/NfieldDomainLanguageTranslationsService.cs
  Library/Services/Implementation/NfieldLanguagesService.cs
  Library/Services/Implementation/NfieldSurveyLanguageTranslationsService.cs
  Library/Services/Implementation/NfieldSurveyRelocationsService.cs
  Library/Services/Implementation/NfieldTranslationsService.cs
  Postman/Nfield Public API.postman_collection.json
  Tests/Services/NfieldDomainLanguageTranslationServiceTests.cs
  Tests/Services/NfieldLanguagesServiceTests.cs
  Tests/Services/NfieldSurveyLanguageTranslationTests.cs
  Tests/Services/NfieldSurveyRelocationsServiceTests.cs
  Tests/Services/NfieldTranslationsServiceTests.cs
  devops.yml
  version.txt
Labels: Team Yellow

#328 AB#108122 Domain response codes: Public api should handle new properties
  Library/Models/DomainResponseCode.cs
  Library/Services/Implementation/NfieldDomainResponseCodesService.cs
  Postman/Environment/DefaultTemplate.postman_environment.json
  Postman/Nfield Public API.postman_collection.json
  Tests/Services/NfieldDomainResponseCodesServiceTests.cs
  version.txt
Labels: Team Purple :space_invader:

#339 Yellow/sp unit tests
  Library/Models/ActivateSpareSamplingPointsResponseModel.cs
  Library/Models/ReplaceSamplingPointWithSpareResponseModel.cs
  Library/Services/INfieldSamplingPointsService.cs
  Library/Services/INfieldSurveysService.cs
  Library/Services/Implementation/NfieldSamplingPointsService.cs
  Postman/Nfield Public API.postman_collection.json
  Tests/Services/NfieldSamplingPointsServiceTests.cs
  version.txt
Labels: Team Yellow

#338 AB#110391 - (sdk) Add spare SP endpoints
  Library/Infrastructure/NfieldSdkInitializer.cs
  Library/Models/ActivateSpareSamplingPointsResponseModel.cs
  Library/Models/ReplaceSamplingPointWithSpareResponseModel.cs
  Library/Models/SamplingPointKind.cs
  Library/Services/INfieldSamplingPointsService.cs
  Library/Services/INfieldSurveysService.cs
  Library/Services/Implementation/NfieldSamplingPointsService.cs
  Postman/Nfield Public API.postman_collection.json
  Tests/Services/NfieldSamplingPointsServiceTests.cs
  version.txt
Labels: Team Yellow, Story :checkered_flag:
