Repository NIPOSoftwareBV/Nfield-SDK, pull requests merged in 2023-04, with the labels that each got.

#410 [AB#118563] Stop using task executor from Public Api: Delete deprecated calls
  Examples/ConsoleApplication/Program.cs
  Library/Extensions/NfieldMediaFilesServiceExtensions.cs
  Library/Services/INfieldMediaFilesService.cs
  Library/Services/INfieldSurveyDataService.cs
  Library/Services/INfieldSurveySampleDataService.cs
  Library/Services/Implementation/NfieldMediaFilesService.cs
  Library/Services/Implementation/NfieldSurveyDataService.cs
  Library/Services/Implementation/NfieldSurveySampleDataService.cs
  Postman/Nfield Public API AAD.postman_collection.json
  Postman/Nfield Public API.postman_collection.json
  Tests/Services/NfieldMediaFilesServiceTests.cs
  Tests/Services/NfieldSurveyDataServiceTests.cs
  Tests/Services/NfieldSurveySampleDataServiceTests.cs
  version.txt
Labels: Team Purple :space_invader:, Story :checkered_flag:

#411 Add delivery api endpoints
  Library/Infrastructure/NfieldSdkInitializer.cs
  Library/Models/Delivery/Amount.cs
  Library/Models/Delivery/CreateDomainSurveyPropertyModel.cs
  Library/Models/Delivery/CreateRepositoryModel.cs
  Library/Models/Delivery/CreateRepositorySubscriptionModel.cs
  Library/Models/Delivery/DomainSurveyModel.cs
  Library/Models/Delivery/DomainSurveyPropertyModel.cs
  Library/Models/Delivery/FirewallRuleModel.cs
  Library/Models/Delivery/RepositoryActivityLogModel.cs
  Library/Models/Delivery/RepositoryConnectionInfo.cs
  Library/Models/Delivery/RepositoryMetricsModel.cs
  Library/Models/Delivery/RepositoryModel.cs
  Library/Models/Delivery/RepositoryPlan.cs
  Library/Models/Delivery/RepositoryStatusListModel.cs
  Library/Models/Delivery/RepositorySubscriptionLogModel.cs
  Library/Models/Delivery/RepositorySurveyModel.cs
  Library/Models/Delivery/RepositoryUserModel.cs
  Library/Models/Delivery/ResourceMetricModel.cs
  Library/Models/Delivery/TimeMetricElementModel.cs
  Library/Models/Delivery/UpdateDomainSurveyPropertyModel.cs
  Library/Services/INfieldDeliveryRepositoriesService.cs
  Library/Services/INfieldDeliveryRepositoryFirewallRulesService.cs
  Library/Services/INfieldDeliveryRepositorySurveysService.cs
  Library/Services/INfieldDeliveryRepositoryUsersService.cs
  Library/Services/INfieldDeliverySettingsService.cs
  Library/Services/INfieldDeliverySurveyPropertiesService.cs
  Library/Services/INfieldDeliverySurveysService.cs
  Library/Services/Implementation/NfieldDeliveryRepositoriesService.cs
  Library/Services/Implementation/NfieldDeliveryRepositoryFirewallRulesService.cs
  Library/Services/Implementation/NfieldDeliveryRepositorySurveysService.cs
  Library/Services/Implementation/NfieldDeliveryRepositoryUsersService.cs
  Library/Services/Implementation/NfieldDeliverySettingsService.cs
  Library/Services/Implementation/NfieldDeliverySurveyPropertiesService.cs
  Library/Services/Implementation/NfieldDeliverySurveysService.cs
  Tests/Services/NfieldDeliveryRepositoriesServiceTests.cs
  Tests/Services/NfieldDeliveryRepositoryFirewallRulesServiceTests.cs
  Tests/Services/NfieldDeliveryRepositorySurveysServiceTests.cs
  Tests/Services/NfieldDeliveryRepositoryUsersServiceTests.cs
  Tests/Services/NfieldDeliverySettingsServiceTests.cs
  Tests/Services/NfieldDeliverySurveyPropertiesServiceTests.cs
  Tests/Services/NfieldDeliverySurveysServiceTests.cs
  version.txt
Labels: Team Green

#412 Get and store data retention settings
  Library/Models/DataRetentionSettings.cs
  Library/Services/INfieldDataRetentionService.cs
  Library/Services/Implementation/NfieldDataRetentionService.cs
  Postman/Nfield Public API AAD.postman_collection.json
  Postman/Nfield Public API.postman_collection.json
  Tests/Services/NfieldDataRetentionTests.cs
Labels: Team Purple :space_invader:, Team Blue

#414 Remove finish state
  Library/Models/SurveyStatus.cs
  Library/Services/INfieldSurveyFieldworkService.cs
  Library/Services/Implementation/NfieldSurveyFieldworkService.cs
  Tests/Services/NfieldSurveyFieldworkServiceTests.cs
  version.txt
Labels: Team Purple :space_invader:

#416 Update to test with console
  Examples/ConsoleApplication/ConsoleApplication.csproj
  Library/Infrastructure/NfieldSdkInitializer.cs
  Library/Models/DataRetentionSettings.cs
  Tests/Services/NfieldDataRetentionTests.cs
Labels: Team Purple :space_invader:, Team Blue

#417 rename closed state to paused
  Library/Models/SurveyStatus.cs
Labels: Team Purple :space_invader:
