Repository NIPOSoftwareBV/Nfield-SDK, pull requests merged in 2023-12, with the labels that each got.

#462 Add language translation warnings
  Library/Models/LanguageTranslations.cs
  Library/Models/TranslationWarning.cs
  version.txt
Labels: Team Red :steam_locomotive:

#461 Fix Delivery endpoint
  Library/Services/Implementation/NfieldDeliveryRepositoryUsersService.cs
  Tests/Services/NfieldDeliveryRepositoryUsersServiceTests.cs
  version.txt
Labels: Team Green

#464 Purple/get single samplerecord
  Library/Services/INfieldSurveySampleService.cs
  Library/Services/Implementation/NfieldSurveySampleService.cs
  Tests/Services/NfieldSurveySampleTests.cs
  version.txt
Labels: Team Purple :space_invader:

#465 [AB#139853] Get single sample record by interview id
  Library/Services/INfieldSurveySampleService.cs
  Library/Services/Implementation/NfieldSurveySampleService.cs
  Postman/Nfield Public API.postman_collection.json
  Tests/Services/NfieldSurveySampleTests.cs
  version.txt
Labels: Team Purple :space_invader:
