Repository NIPOSoftwareBV/Nfield-SDK, pull requests merged in 2023-06, with the labels that each got.

#424 Domain API: Release V2 Block 1/2
  Postman/Nfield Public API Domain V2.postman_collection.json
Labels: Team Yellow

#425 Domain API: Release V2 Block 1/2
  Postman/Nfield Public API Domain V2.postman_collection.json
Labels: Team Yellow

#426 Add 'UseLegacyParser' to script post method.
  Library/Models/SurveyScript.cs
Labels: Team White

#428 Custom column parameters added
  Library/Models/SurveyDataRequest.cs
  version.txt
Labels: Team Purple :space_invader:

#432 Convert to async
  Library/Extensions/NfieldConnectionClientExtensions.cs
Labels: Team Purple :space_invader:

#431 SDK release pipeline
  Pipelines/Scripts/GetNugetVersion.ps1
  Pipelines/YmlTemplates/deploy.yml
  Pipelines/YmlTemplates/postBuildSteps.yml
  Pipelines/YmlTemplates/runUnitTests.yml
  Pipelines/build.yml
  Pipelines/deploy-nuget.yml
  README.md
  devops.yml
  publish-release.ps1
Labels: Team Yellow

#429 Add Events Api endpoints
  Library/Infrastructure/NfieldSdkInitializer.cs
  Library/Models/Events/CreateEventSubscriptionModel.cs
  Library/Models/Events/EventSubscriptionModel.cs
  Library/Models/Events/UpdateEventSubscriptionModel.cs
  Library/Services/INfieldEventSubscriptionsService.cs
  Library/Services/Implementation/NfieldEventSubscriptionsService.cs
  Tests/Services/NfieldEventSubscriptionsServiceTests.cs
  version.txt
Labels: Story :checkered_flag:, Team Green

#433 Update Postman Collections for Events API
  Postman/Nfield Public API AAD.postman_collection.json
  Postman/Nfield Public API.postman_collection.json
Labels: Story :checkered_flag:, Team Green
