Repository NIPOSoftwareBV/Nfield-SDK, pull requests merged in 2023-01, with the labels that each got.

#381 [AB#118592] Milestone 1.1 - Marking the surveys as "will be stopped" and "will be deleted"
  Library/Models/SurveyResources.cs
  Tests/Services/NfieldSurveyResourcesServiceTests.cs
  version.txt
Labels: Team Purple :space_invader:

#382 [Fix] Disable blocking tests
  devops.yml
Labels: Team Purple :space_invader:

#379 Add Postman Documentation for Repository User (Delivery API)
  Postman/Nfield Public API AAD.postman_collection.json
  Postman/Nfield Public API.postman_collection.json
Labels: Story :checkered_flag:, Team Green

#384 Add theme binary
  Library/Services/INfieldThemesService.cs
  Library/Services/Implementation/NfieldThemesService.cs
  Tests/Services/NfieldThemesServiceTests.cs
  version.txt
Labels: Team Blue

#383 Add domain api postman collection
  Postman/Environment/DefaultTemplate.postman_environment.json
  Postman/Nfield Domain API.postman_collection.json
  Postman/Nfield Public API AAD.postman_collection.json
  Postman/Nfield Public API.postman_collection.json
Labels: Team Yellow

#385 Improve Domain API testing: Create domain api postman collection
  Postman/Environment/DefaultTemplate.postman_environment.json
  Postman/Nfield Domain API.postman_collection.json
  Postman/Nfield Public API AAD.postman_collection.json
  Postman/Nfield Public API.postman_collection.json
Labels: Team Yellow

#386 Update domain api postman collection with offices
  Postman/Nfield Domain API.postman_collection.json
  Postman/Nfield Public API.postman_collection.json
Labels: Team Yellow

#388 Add background and search fields settings controllers to the postman collection
  Postman/Nfield Domain API.postman_collection.json
Labels: Team Yellow
