Repository NIPOSoftwareBV/Nfield-SDK, pull requests merged in 2023-03, with the labels that each got.

#397 Implement missed methods to SDK to allow to deprecate old ones. AB#124372
  Library/Infrastructure/NfieldSdkInitializer.cs
  Library/Services/INfieldCapiInterviewersService.cs
  Library/Services/INfieldDomainInterviewersWorklogService.cs
  Library/Services/INfieldInterviewersService.cs
  Library/Services/Implementation/NfieldCapiInterviewersService.cs
  Library/Services/Implementation/NfieldDomainInterviewersWorklogService.cs
  Tests/Services/NfieldCapiInterviewersServiceTests.cs
  Tests/Services/NfieldDomainInterviewersWorklogServiceTests.cs
  version.txt
Labels: Team Yellow, Story :checkered_flag:

#398 get and set owner as part of the general settings
  Library/Models/SurveyGeneralSetting.cs
  Library/Services/INfieldSurveyGeneralSettingsService.cs
  Library/Services/Implementation/NfieldSurveyGeneralSettingsService.cs
  Tests/Services/NfieldSurveyGeneralSettingsServiceTests.cs
  version.txt
Labels: Team Purple :space_invader:

#400 Add information about deprecated endpoints
  Postman/Nfield Public API.postman_collection.json
Labels: Team Purple :space_invader:, Team Blue

#399 [AB#124223] SurveyOtherSettings should be refactored - Move owner
  Library/Models/SurveyGeneralSetting.cs
  Library/Services/INfieldSurveyGeneralSettingsService.cs
  Library/Services/Implementation/NfieldSurveyGeneralSettingsService.cs
  Postman/Nfield Public API.postman_collection.json
  Tests/Services/NfieldSurveyGeneralSettingsServiceTests.cs
  version.txt
Labels: Team Purple :space_invader:

#405 AB#124379 Create Me Service and respective unit tests
  Library/Infrastructure/NfieldSdkInitializer.cs
  Library/Models/UserRoleModel.cs
  Library/Services/INfieldMeService.cs
  Library/Services/Implementation/NfieldMeService.cs
  Tests/Services/NfieldMeServiceTest.cs
Labels: Team Yellow

#407 Add auditlog parameter
  Library/Models/SurveyDataRequest.cs
Labels: Team Purple :space_invader:

#406 AB#124379 Yellow/ci nfield me service
  Library/Infrastructure/NfieldSdkInitializer.cs
  Library/Models/UserRoleModel.cs
  Library/Services/INfieldMeService.cs
  Library/Services/Implementation/NfieldMeService.cs
  Tests/Services/NfieldMeServiceTest.cs
Labels: Team Yellow

#409 Deprecated removed
  Postman/Nfield Public API AAD.postman_collection.json
  Postman/Nfield Public API.postman_collection.json
Labels: Team Purple :space_invader:
