Repository NIPOSoftwareBV/Nfield-SDK, pull requests merged in 2023-07, with the labels that each got.

#434 AB#130241 In data download jobs, allow filtering on any specified sample table field
  Library/Extensions/NfieldConnectionClientExtensions.cs
  Library/Models/SurveyDataRequest.cs
  version.txt
Labels: Team Purple :space_invader:

#435 release pipeline improvments
  Nfield.SDK.sln
  Pipelines/YmlTemplates/deploy.yml
  Pipelines/YmlTemplates/runUnitTests.yml
Labels: Team Yellow, Story :checkered_flag:

#437 Nuget dependencies added to the package
  Library/Models/CapiInterviewers/CapiInterviewer.cs
  Pipelines/build.yml
Labels: Team Yellow

#436 Pipeline Improvement. ab#130932
  Nfield.SDK.sln
  Pipelines/YmlTemplates/deploy.yml
  Pipelines/YmlTemplates/runUnitTests.yml
Labels: Team Yellow, Story :checkered_flag:

#438 Remove CopyableSurveyConfiguration from AddFromBlueprintAsync
  Library/Services/INfieldSurveysService.cs
  Library/Services/Implementation/NfieldSurveysService.cs
  version.txt
Labels: Team Red :steam_locomotive:

#439 Forgotten stuff
  Library/Models/CopyableSurveyConfiguration.cs
  Tests/Services/NfieldSurveysServiceTests.cs
Labels: Team Red :steam_locomotive:

#442 Fix events models
  Library/Models/Events/CreateEventSubscriptionModel.cs
  Library/Models/Events/CreatedEventSubscriptionModel.cs
  Library/Models/Events/UpdateEventSubscriptionModel.cs
  Library/Services/INfieldEventSubscriptionsService.cs
  Library/Services/Implementation/NfieldEventSubscriptionsService.cs
  Tests/Services/NfieldEventSubscriptionsServiceTests.cs
Labels: Team Green

#441 AB#131135 Add questionnaire script to blueprint
  Library/Models/CopyableSurveyConfiguration.cs
  Library/Services/INfieldSurveysService.cs
  Library/Services/Implementation/NfieldSurveysService.cs
  Tests/Services/NfieldSurveysServiceTests.cs
  version.txt
Labels: Team Red :steam_locomotive:, Story :checkered_flag:

#444 AB#131261 remove SecurityCodeScan.VS2019
  Library/Nfield.SDK.csproj
  version.txt
Labels: Team White, Story :checkered_flag:

#443 Move SDK and Quota YMLs from their own repos to nfield-tools.
  Pipelines/Scripts/GetNugetVersion.ps1
  Pipelines/YmlTemplates/deploy.yml
  Pipelines/YmlTemplates/postBuildSteps.yml
  Pipelines/YmlTemplates/runUnitTests.yml
  Pipelines/build.yml
  Pipelines/deploy-nuget.yml
Labels: Team Yellow

#447 configure await false
  Library/Infrastructure/ActiveDirectoryNfieldHttpClient.cs
  Library/Infrastructure/DefaultNfieldHttpClient.cs
  Library/Infrastructure/NfieldConnection.cs
  Library/Services/Implementation/NfieldBlacklistService.cs
  Library/Services/Implementation/NfieldCatiInterviewersService.cs
  Library/Services/Implementation/NfieldDataRetentionService.cs
  Library/Services/Implementation/NfieldDomainInterviewersWorklogService.cs
  Library/Services/Implementation/NfieldInterviewersService.cs
  Library/Services/Implementation/NfieldLocalUserService.cs
  Library/Services/Implementation/NfieldMediaFilesService.cs
  Library/Services/Implementation/NfieldRequestsService.cs
  Library/Services/Implementation/NfieldSurveyGroupAssignmentsService.cs
  Library/Services/Implementation/NfieldSurveyGroupService.cs
  Library/Services/Implementation/NfieldSurveySampleDataService.cs
  Library/Services/Implementation/NfieldThemesService.cs
Labels: Team Yellow

#446 [AB#131179] Report versions with counts in public api
  Library/Models/SurveyVersion.cs
  Nfield.SDK.sln
  Pipelines/deploy-nuget.yml
  Tests/Services/NfieldSurveyVersionsServiceTests.cs
  version.txt
Labels: Team Purple :space_invader:

#448 Add configure await false to await calls.
  Library/Infrastructure/ActiveDirectoryNfieldHttpClient.cs
  Library/Infrastructure/DefaultNfieldHttpClient.cs
  Library/Infrastructure/NfieldConnection.cs
  Library/Services/Implementation/NfieldBlacklistService.cs
  Library/Services/Implementation/NfieldCatiInterviewersService.cs
  Library/Services/Implementation/NfieldDataRetentionService.cs
  Library/Services/Implementation/NfieldDomainInterviewersWorklogService.cs
  Library/Services/Implementation/NfieldInterviewersService.cs
  Library/Services/Implementation/NfieldLocalUserService.cs
  Library/Services/Implementation/NfieldMediaFilesService.cs
  Library/Services/Implementation/NfieldRequestsService.cs
  Library/Services/Implementation/NfieldSurveyGroupAssignmentsService.cs
  Library/Services/Implementation/NfieldSurveyGroupService.cs
  Library/Services/Implementation/NfieldSurveySampleDataService.cs
  Library/Services/Implementation/NfieldThemesService.cs
Labels: Team Yellow, Story :checkered_flag:
