Repository NIPOSoftwareBV/Nfield-SDK, pull requests merged in 2024-06, with the labels that each got.

#505 Remove properties from patch
  Postman/Nfield Public API Domain V2.postman_collection.json
  Postman/Nfield Public API.postman_collection.json
Labels: Team Red :steam_locomotive:

#508 Add blueprints to postman
  Postman/Nfield Public API.postman_collection.json
Labels: Team Red :steam_locomotive:, Story :checkered_flag:

#509 Red/update comments and tests
  Library/Models/DomainPasswordSettings.cs
  Tests/Services/NfieldDomainPasswordSettingsServiceTests.cs
  version.txt
Labels: Team Red :steam_locomotive:

#506 [AB#144565] Red/Cleanup: Remove password strength dropdown
  Library/Models/DomainPasswordSettings.cs
  Postman/Nfield Public API Domain V2.postman_collection.json
  Postman/Nfield Public API.postman_collection.json
  Tests/Services/NfieldDomainPasswordSettingsServiceTests.cs
Labels: Team Red :steam_locomotive:

#510 update-trackers
  Library/Infrastructure/NfieldSdkInitializer.cs
  Library/Models/Survey.cs
  Library/Services/INfieldParentSurveyService.cs
  Library/Services/Implementation/NfieldParentSurveyService.cs
  Tests/Services/NfieldParentSurveyServiceTests.cs
  version.txt
Labels: Team Purple :space_invader:, Team Blue

#513 update-postman
  Postman/Nfield Public API.postman_collection.json
Labels: Team Purple :space_invader:, Team Blue
