Repository NIPOSoftwareBV/Nfield-SDK, pull requests merged in 2024-03, with the labels that each got.

#481 Add download hints api
  Library/Infrastructure/NfieldSdkInitializer.cs
  Library/Services/INfieldSurveySimulationHintsService.cs
  Library/Services/Implementation/NfieldSurveySimulationHintsService.cs
  Postman/Nfield Public API.postman_collection.json
  Tests/Services/NfieldSurveySimulationHintsTests.cs
Labels: Team Purple :space_invader:, Team Blue

#482 update collection
  Postman/Nfield Public API.postman_collection.json
Labels: Team Purple :space_invader:

#486 update-model
  Library/Models/SurveyResources.cs
  Tests/Services/NfieldSurveyResourcesServiceTests.cs
  version.txt
Labels: Team Purple :space_invader:, Team Blue

#480 AB#140570 Use new table storage methods/types in project-glu-api
  CodeAnalysis/NipoSoftware.DefaultProjectRules.targets
  Library/Nfield.SDK.csproj
  Nfield.SDK.sln
  Tests/Nfield.SDK.Tests.csproj
  version.txt
Labels: Team White, Story :checkered_flag:

#488 AB#145644 return activity Id from MediaFileUpload
  Library/Services/INfieldMediaFilesService.cs
  Library/Services/Implementation/NfieldMediaFilesService.cs
  version.txt
Labels: Team Yellow

#487 AB#142998 Show the 'Exclude this survey from automatic deletion and stoppage' status in the Surveys/Manage page of Nfield Manager
  Library/Models/SurveyResources.cs
  Tests/Services/NfieldSurveyResourcesServiceTests.cs
  version.txt
Labels: Team Purple :space_invader:, Team Blue, Story :checkered_flag:

#489 AB#142187 Yellow/ci uplload zip fix
  Library/Services/INfieldMediaFilesService.cs
  Library/Services/Implementation/NfieldMediaFilesService.cs
  version.txt
Labels: Team Yellow

#485 Added start simulation functionality
  Library/Extensions/NfieldConnectionClientExtensions.cs
  Library/Models/InterviewSimulation.cs
  Library/Models/InterviewSimulationFiles.cs
  Library/Models/InterviewSimulationResult.cs
  Library/Services/INfieldSurveyInterviewSimulationService.cs
  Library/Services/Implementation/NfieldSurveyInterviewSimulationService.cs
Labels: Team Purple :space_invader:

#491 return content
  Library/Services/INfieldSurveyInterviewSimulationService.cs
  Library/Services/Implementation/NfieldSurveyInterviewSimulationService.cs
Labels: Team Purple :space_invader:

#492 quota version
  Library/Nfield.SDK.csproj
Labels: Team Yellow

#494 Fixed test
  Library/Services/INfieldSurveyInterviewSimulationService.cs
  Tests/Services/NfieldSurveyInterviewSimulationTests.cs
Labels: Team Purple :space_invader:

#493 Update Nfield Public API.postman_collection.json
  Postman/Nfield Public API.postman_collection.json
Labels: Team Yellow
