Repository NIPOSoftwareBV/Nfield-SDK, pull requests merged in 2024-02, with the labels that each got.

#475 AB#143532 Update Nfield Public API.postman_collection.json
  Postman/Nfield Public API.postman_collection.json
Labels: Team Yellow

#478 update-sdk
  Library/Services/INfieldExternalApisService.cs
  Library/Services/Implementation/NfieldExternalApisService.cs
  Postman/Nfield Public API.postman_collection.json
  Tests/Services/NfieldExternalApisServiceTests.cs
Labels: Team Purple :space_invader:, Team Blue

#479 AB#137553 Remove option to create new *GETDATA endpoint through Manager and Public API
  Library/Services/INfieldExternalApisService.cs
  Library/Services/Implementation/NfieldExternalApisService.cs
  Postman/Nfield Public API.postman_collection.json
  Tests/Services/NfieldExternalApisServiceTests.cs
  version.txt
Labels: Team Purple :space_invader:, Team Blue, Story :checkered_flag:
