Repository NIPOSoftwareBV/Nfield-SDK, pull requests merged in 2024-07, with the labels that each got.

#514 .Net8: Migrate MediaFiles, MediaFilesCount + QuotaVersions controllers
  Library/Services/Implementation/NfieldMediaFilesService.cs
Labels: Team Yellow

#515 .Net8: Migrate MediaFiles, MediaFilesCount + QuotaVersions controllers
  Library/Services/Implementation/NfieldMediaFilesService.cs
  Tests/Services/NfieldMediaFilesServiceTests.cs
  version.txt
Labels: Team Yellow

#511 Tracker surveys extension: Create and list trackers and waves from public api
  Library/Infrastructure/NfieldSdkInitializer.cs
  Library/Services/INfieldParentSurveyService.cs
  Library/Services/INfieldParentSurveyWavesService.cs
  Library/Services/Implementation/NfieldParentSurveyService.cs
  Library/Services/Implementation/NfieldParentSurveyWavesService.cs
  Postman/Nfield Public API.postman_collection.json
  Tests/Services/NfieldParentSurveyServiceTests.cs
  Tests/Services/NfieldParentSurveyWavesServiceTests.cs
  version.txt
Labels: Team Purple :space_invader:, Team Blue, Story :checkered_flag:

#517 Add EnableRespondentsGateway to survey model
  Library/Models/Survey.cs
  version.txt
Labels: Team Green

#520 Fix url encoding
  Library/Services/Implementation/NfieldMediaFilesService.cs
Labels: Team Yellow

#522 Fix url encoding
  Library/Services/Implementation/NfieldMediaFilesService.cs
  version.txt
Labels: Team Yellow

#521 version 2.89
  version.txt
Labels: Team Yellow
