Repository NIPOSoftwareBV/Nfield-SDK, pull requests merged in 2024-09, with the labels that each got.

#530 Media download filter
  Library/Models/SurveyDataRequest.cs
  version.txt
Labels: Team Yellow

#533 Yellow/align unit
  Library/Models/WorkPackageTargetCounts.cs
  Library/Services/INfieldSurveyInterviewerDistributeWorkpackageTargetsService.cs
  Library/Services/INfieldSurveyInterviewerQuotaLevelTargetsService.cs
  Library/Services/Implementation/NfieldSurveyInterviewerDistributeWorkpackageTargetsService.cs
  Library/Services/Implementation/NfieldSurveyInterviewerQuotaLevelTargetsService.cs
  Library/Services/Implementation/NfieldSurveyInterviewersAssignmentsService.cs
  Tests/Services/NfieldCapiInterviewersServiceTests.cs
  Tests/Services/NfieldSurveyInterviewerAssignmentServiceTests.cs
  Tests/Services/NfieldSurveyInterviewerDistributeWorkpackageTargetsServiceTests.cs
  Tests/Services/NfieldSurveyInterviewerQuotaLevelTargetsServiceTest.cs
Labels: Team Yellow

#534 Manual tests support
  Library/Infrastructure/NfieldSdkInitializer.cs
  Library/Models/ManualTestSurveyResult.cs
  Library/Models/StartCreateManualTestSurvey.cs
  Library/Models/StartCreateManualTestSurveyFile.cs
  Library/Models/SurveyManualTest.cs
  Library/Services/INfieldManualTestsService.cs
  Library/Services/INfieldSurveyManualTestsService.cs
  Library/Services/Implementation/NfieldManualTestsService.cs
  Library/Services/Implementation/NfieldSurveyManualTestsService.cs
  Tests/Services/NfieldManualTestsServiceTests.cs
  Tests/Services/NfieldSurveyManualTestsServiceTests.cs
Labels: Team Purple :space_invader:

#536 Move method to other controller
  Library/Infrastructure/NfieldSdkInitializer.cs
  Library/Services/INfieldManualTestsService.cs
  Library/Services/INfieldSurveyManualTestsService.cs
  Library/Services/Implementation/NfieldManualTestsService.cs
  Library/Services/Implementation/NfieldSurveyManualTestsService.cs
  Tests/Services/NfieldManualTestsServiceTests.cs
  Tests/Services/NfieldSurveyManualTestsServiceTests.cs
Labels: Team Purple :space_invader:

#535 Test surveys: List and create test surveys from public api
  Library/Infrastructure/NfieldSdkInitializer.cs
  Library/Models/ManualTestSurveyResult.cs
  Library/Models/StartCreateManualTestSurvey.cs
  Library/Models/StartCreateManualTestSurveyFile.cs
  Library/Models/SurveyManualTest.cs
  Library/Services/INfieldSurveyManualTestsService.cs
  Library/Services/Implementation/NfieldSurveyManualTestsService.cs
  Tests/Services/NfieldSurveyManualTestsServiceTests.cs
  version.txt
Labels: Team Purple :space_invader:, Story :checkered_flag:

#537 fix hanging tests on build server
  Tests/Services/NfieldSurveyManualTestsServiceTests.cs
Labels: Team Purple :space_invader:

#538 setting enum
  Library/Models/SurveySettingEnum.cs
  Library/Models/SurveySettings.cs
  Library/Services/INfieldSurveySettingsService.cs
  Library/Services/Implementation/NfieldSurveySettingsService.cs
Labels: Team Yellow
