Repository NIPOSoftwareBV/Nfield-SDK, pull requests merged in 2024-05, with the labels that each got.

#502 Removed external api update
  Library/Services/INfieldExternalApisService.cs
  Library/Services/Implementation/NfieldExternalApisService.cs
  Postman/Nfield Public API.postman_collection.json
  Tests/Services/NfieldExternalApisServiceTests.cs
  version.txt
Labels: Team Purple :space_invader:

#503 [AB#137555] Remove option to update *GETDATA endpoints
  Library/Services/INfieldExternalApisService.cs
  Library/Services/Implementation/NfieldExternalApisService.cs
  Postman/Nfield Public API.postman_collection.json
  Tests/Services/NfieldExternalApisServiceTests.cs
  version.txt
Labels: Team Purple :space_invader:, Story :checkered_flag:

#504 Fix postman collection
  Postman/Nfield Public API AAD.postman_collection.json
  Postman/Nfield Public API.postman_collection.json
Labels: Team Yellow
