Repository NIPOSoftwareBV/Nfield-SDK, pull requests merged in 2025-02, with the labels that each got.

#548 Allow NRG Surveys to be created from a blueprint
  Library/Services/INfieldSurveysService.cs
  Library/Services/Implementation/NfieldSurveysService.cs
  Tests/Services/NfieldSurveysServiceTests.cs
  version.txt
Labels: Story :checkered_flag:, Team Green

#550 Updated Survey model
  Library/Models/Survey.cs
  Tests/Services/NfieldParentSurveyServiceTests.cs
  version.txt
Labels: Team Purple :space_invader:

#552 New Sampling point features Create and Patch
  Library/Models/SamplingPoint.cs
  Library/Models/SamplingPointCustomDataModel.cs
  Tests/Services/NfieldSamplingPointsServiceTests.cs
Labels: Team Yellow
